services:

  postgres_airflow:
    image: postgres:14
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_airflow_data:/var/lib/postgresql/data

  postgres_etl:
    image: postgres:14
    container_name: postgres_etl
    environment:
      POSTGRES_USER: ${ETL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ETL_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ETL_POSTGRES_DB}
    ports:
      - "5433:5432" 
    volumes:
      - pg_etl_data:/var/lib/postgresql/data

  airflow-webserver: 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@postgres_airflow/${AIRFLOW_POSTGRES_DB}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com && airflow webserver"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres_airflow

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@postgres_airflow/${AIRFLOW_POSTGRES_DB}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    env_file:
      - .env
    depends_on:
      - airflow-webserver
    command: scheduler

volumes:
  pg_airflow_data:
  pg_etl_data: