version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: spotify_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: spotify_user
      POSTGRES_PASSWORD: spotify_pass
      POSTGRES_DB: spotify_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: